# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 632f0e9e1e2a96eb975db61ecef1d90631bb3e61450a29ac0a0a6fdc259ddf1fecc1e83d9ec26b171f98e75fe982468760d55bc28046512176243f25efe6e131

test:
  secret_key_base: 691fe0996c00a538559456843a531fb6050da30668f1cbaf9187ac7b63874d5de78be4e2b6e0b2248a0e5ab4808c0dcd38c61cd4ddb368a965b46aaca14e79b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
